
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbxfmfelalpycznsatxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpieGZtZmVsYWxweWN6bnNhdHhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMDU3ODYsImV4cCI6MjA2NjY4MTc4Nn0.gjwLoubonQEIskmwV7Dlct6uVRjrAr-qR88hdKh2l-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
